const characters = {
    miyamura: {
        kana: ["みやむら", "ミヤムラ"],
        answer: "Miyamura",
        series: "Horimiya",
        kanji: "宮村 伊澄",
        romaji: "Miyamura Izumi",
    },
    hori: {
        kana: ["ほり", "ホリ"],
        answer: "Hori",
        series: "Horimiya",
        kanji: "堀 京子",
        romaji: "Hori Kyouko",
    },
    yuuji: {
        kana: ["ゆうじ", "ユウジ"],
        answer: "Yuuji",
        series: "Toradora",
        kanji: "高須 龍児",
        romaji: "Takasu Ryuugi",
    },
    taiga: {
        kana: ["たいが", "タイガ"],
        answer: "Taiga",
        series: "Toradora",
        kanji: "逢坂 大河",
        romaji: "Aisaka Taiga",
    },
    naruto: {
        kana: ["なると", "ナルト"],
        answer: "Naruto",
        series: "Naruto",
        kanji: "うずまき ナルト",
        romaji: "Uzumaki Naruto",
    },
    sasuke: {
        kana: ["さすけ", "サスケ"],
        answer: "Sasuke",
        series: "Naruto",
        kanji: "うちは サスケ",
        romaji: "Uchiha Sasuke",
    },
    sakura: {
        kana: ["さくら", "サクラ"],
        answer: "Sakura",
        series: "Naruto",
        kanji: "春野 サクラ",
        romaji: "Haruno Sakura",
    },
    kurisu: {
        kana: ["くりす", "クリス"],
        answer: "Kurisu",
        series: "Steins;Gate",
        kanji: "牧瀬 紅莉栖",
        romaji: "Makise Kurisu",
    },
    rintaro: {
        kana: ["りんたろう", "リンタロウ"],
        answer: "Rintarou",
        series: "Steins;Gate",
        kanji: "岡部 倫太郎",
        romaji: "Okabe Rintarou",
    },
    // zoro: {
    //     kana: ["ぞろ", "ゾロ"],
    //     answer: "Zoro",
    //     series: "One Piece",
    //     kanji: "ロロノア・ゾロ",
    //     romaji: "Roronoa Zoro",
    // },
    // luffy: {
    //     kana: ["るふぃ", "ルフィ"],
    //     answer: "Luffy",
    //     series: "One Piece",
    //     kanji: "モンキー・D・ルフィ",
    //     romaji: "Monkey D. Luffy",
    // },
    // sanji: {
    //     kana: ["さんじ", "サンジ"],
    //     answer: "Sanji",
    //     series: "One Piece",
    //     kanji: "ヴィンスモーク・サンジ",
    //     romaji: "Vinsmoke Sanji",
    // },
    // tanjiro: {
    //     kana: ["たんじろう", "タンジロウ"],
    //     answer: "Tanjiro",
    //     series: "Demon Slayer",
    //     kanji: "竈門 炭治郎",
    //     romaji: "Kamado Tanjiro",
    // },
    // nezuko: {
    //     kana: ["ねずこ", "ネズコ"],
    //     answer: "Nezuko",
    //     series: "Demon Slayer",
    //     kanji: "竈門 禰豆子",
    //     romaji: "Kamado Nezuko",
    // },
    // gojo: {
    //     kana: ["ごじょう", "ゴジョウ"],
    //     answer: "Gojo",
    //     series: "Jujutsu Kaisen",
    //     kanji: "五条 悟",
    //     romaji: "Gojo Satoru",
    // },
    // meimei: {
    //     kana: ["めいめい", "メイメイ"],
    //     answer: "Mei Mei",
    //     series: "Jujutsu Kaisen",
    //     kanji: "メイメイ",
    //     romaji: "Mei Mei",
    // },
    // sukuna: {
    //     kana: ["すくな", "スクナ"],
    //     answer: "Sukuna",
    //     series: "Jujutsu Kaisen",
    //     kanji: "両面 宿儺",
    //     romaji: "Ryoumen Sukuna",
    // }
};
